# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 94ba584d363c362db0cb0ea1ef978e6d5e3619f640dea5ad69d3fa3a1f339d5ea5b87926c8e2c01df99d703d6581043fdcade682f4d178b31ec7482afc432782

test:
  secret_key_base: 5989a96428eb94286c494e0bb575ba72c0cca8d621b7175b6cd7135e168173288434de7d0da33afd9562fe0486bdc19203452ece0086e68ceb62998943ed3969

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
